// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/portfolio-data.ts
var profile = {
  name: "SrinivaS",
  title: "Product Manager",
  location: "Visakhapatnam, Andhra Pradesh, India",
  summary: "Product Manager focused on transforming ideas into impactful products. Combines data-driven decision making with user-centric design, ensuring every product delivers real value to end users while achieving business objectives.",
  coreExpertise: [
    "Product Strategy",
    "Roadmapping",
    "User Research",
    "Data Analytics",
    "AI/ML Product Development",
    "Agile/Scrum",
    "Stakeholder Management",
    "Go-to-Market",
    "UX Collaboration",
    "Technical Product Management"
  ],
  achievements: [
    {
      title: "Product Launches",
      description: "15+ successful product launches with 2M+ users"
    },
    {
      title: "Growth Impact",
      description: "300% user growth and 40% revenue increase"
    },
    {
      title: "Team Leadership",
      description: "Led cross-functional teams of 20+ professionals"
    }
  ],
  resumeUrl: "/cv-srinivas.pdf"
};
var projects = [
  {
    id: 1,
    title: "AI-Powered Analytics Platform",
    category: "Enterprise SaaS",
    role: "Senior Product Manager",
    description: "Revolutionary AI assistant that analyzes business data and provides actionable insights. Increased user productivity by 60% and reduced analysis time from hours to minutes.",
    impact: "2M+ users, 60% productivity increase",
    technologies: ["AI/ML", "React", "Python", "AWS"]
  },
  {
    id: 2,
    title: "Next-Gen Fintech Mobile App",
    category: "Fintech",
    role: "Lead Product Manager",
    description: "Complete financial ecosystem with AI-driven insights, seamless payments, and personalized investment recommendations. Achieved 300% user growth in 12 months.",
    impact: "300% user growth, $5M ARR",
    technologies: ["React Native", "Node.js", "Blockchain", "ML"]
  },
  {
    id: 3,
    title: "Healthcare Data Intelligence",
    category: "HealthTech",
    role: "Product Manager",
    description: "HIPAA-compliant platform that aggregates patient data across systems, providing real-time insights for healthcare providers. Improved patient outcomes by 40%.",
    impact: "40% improved outcomes, 100+ hospitals",
    technologies: ["Vue.js", "FHIR", "Azure", "Analytics"]
  }
];
var skillCategories = [
  {
    title: "Product Strategy",
    skills: [
      { name: "Roadmapping", level: 95 },
      { name: "Market Research", level: 90 },
      { name: "Competitive Analysis", level: 88 },
      { name: "Product Vision", level: 93 }
    ]
  },
  {
    title: "Analytics & Data",
    skills: [
      { name: "Data Analytics", level: 92 },
      { name: "A/B Testing", level: 89 },
      { name: "SQL", level: 85 },
      { name: "Product Metrics", level: 94 }
    ]
  },
  {
    title: "Leadership",
    skills: [
      { name: "Team Management", level: 91 },
      { name: "Stakeholder Management", level: 93 },
      { name: "Cross-functional Collaboration", level: 96 },
      { name: "Agile/Scrum", level: 88 }
    ]
  },
  {
    title: "Technical",
    skills: [
      { name: "API Integration", level: 83 },
      { name: "Technical Documentation", level: 90 },
      { name: "System Architecture", level: 79 },
      { name: "Cloud Platforms", level: 82 }
    ]
  }
];
var tools = [
  "Figma",
  "Jira",
  "Confluence",
  "Mixpanel",
  "Amplitude",
  "Tableau",
  "Notion",
  "Slack",
  "GitHub",
  "Balsamiq",
  "Google Analytics",
  "Hotjar"
];
var certifications = [
  "Certified UI/UX Designer",
  "Google Analytics Certified",
  "Figma Expert Diploma",
  "Product Management Certificate"
];
var contact = {
  email: "ssai55030@gmail.com",
  phone: "+91 7287070114",
  location: "Visakhapatnam, Andhra Pradesh",
  social: {
    linkedin: "https://www.linkedin.com/in/mssrinivas1511",
    twitter: "https://twitter.com/SaiSrinivaS2371",
    github: "https://github.com/mssrinivas1511",
    instagram: "https://www.instagram.com/nivas_1511/"
  }
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get the portfolio owner's public profile: name, title, location, summary, core expertise and headline achievements.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: { profile }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "List the featured portfolio projects, with role, impact, category and technologies. Optionally filter by category or a free-text query.",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter, e.g. 'Fintech', 'HealthTech', 'Enterprise SaaS'."),
    query: z.string().optional().describe("Optional free-text search across title, description and technologies.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, query }) => {
    const needle = query?.trim().toLowerCase();
    const cat = category?.trim().toLowerCase();
    const results = projects.filter((project) => {
      const matchesCategory = !cat || project.category.toLowerCase().includes(cat);
      const haystack = [project.title, project.description, project.role, ...project.technologies].join(" ").toLowerCase();
      const matchesQuery = !needle || haystack.includes(needle);
      return matchesCategory && matchesQuery;
    });
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, projects: results }
    };
  }
});

// src/lib/mcp/tools/get-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_skills_default = defineTool3({
  name: "get_skills",
  title: "Get skills and expertise",
  description: "Get skill categories with proficiency levels, plus the tools and certifications listed on the portfolio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = { skillCategories, tools, certifications };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get the public contact details and social profile links published on the portfolio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: { contact }
  })
});

// src/lib/mcp/tools/get-resume.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_resume_default = defineTool5({
  name: "get_resume",
  title: "Get resume link",
  description: "Get the path to the portfolio owner's downloadable resume (PDF).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `Resume (PDF) is available at ${profile.resumeUrl} on the portfolio site.`
      }
    ],
    structuredContent: { resumeUrl: profile.resumeUrl }
  })
});

// src/lib/mcp/index.ts
var projectRef = "rbeiqnquqmabtovdtzlm";
var mcp_default = defineMcp({
  name: "mssrinivas1511",
  title: "mssrinivas1511",
  version: "0.1.0",
  instructions: "Tools for SrinivaS's product management portfolio. Use `get_profile` for background and expertise, `list_projects` for featured case studies (optionally filtered), `get_skills` for skills, tools and certifications, `get_contact_info` for contact and social links, and `get_resume` for the downloadable resume URL. Callers must sign in to this app via OAuth.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_projects_default, get_skills_default, get_contact_info_default, get_resume_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
